content:
  - name: blog
    label: Blogposts
    path: src/content/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string