media:
  input: src/images
  output: /src/images
  
content:
  - name: blog
    label: Blogposts
    path: src/content/blog
    type: collection
    view:
      fields: [ title, slug, pubDate, image ]
      primary: title
      sort: [ pubDate, title ]
      default:
        search: ''
        sort: title
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: description
        label: Description
        type: string
      - name: pubDate
        label: Publication Date
        type: date
      - name: updatedDate
        label: Updated Date
        type: date
        required: false
      - name: author
        label: Author
        type: string
        required: false
      - name: image
        label: Featured Image
        type: image
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Content
        type: rich-text